package database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class DatabaseConfig {
    private static Connection connection;
    private static DatabaseConfig databaseConfig;

    private DatabaseConfig() {
        try {
            connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/beauty",
                    "postgres", "postgres");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static DatabaseConfig getInstance(){
        if(databaseConfig == null)
            databaseConfig = new DatabaseConfig();
        return databaseConfig;
    }

    public Connection getConnection(){
        return connection;
    }

    /* admins
    CREATE TABLE admins (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login varchar NOT NULL,
    password varchar NOT NULL
    );
    INSERT INTO admins (login,password) VALUES ('admin1','admin1');
    INSERT INTO admins (login,password) VALUES ('admin2','admin2');
     */
    /* clients
    CREATE TABLE clients (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    phone varchar NOT NULL
    );
     */
    /* complaints
    CREATE TABLE complaints (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry integer NOT NULL,
    state varchar NOT NULL,
    text varchar NOT NULL,
    explanatory varchar,
    decision_client varchar,
    decision_master varchar
    );

    INSERT INTO complaints (entry, state, text) VALUES (7, 'OPENED', 'Жалоба');
     */
    /* masters
     CREATE TABLE masters (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    login varchar NOT NULL,
    password varchar NOT NULL,
    services varchar NOT NULL
    );
     */
    /* entries
     CREATE TABLE entries (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_date timestamp NOT NULL,
    master integer NOT NULL,
    state varchar NOT NULL,
    services integer[] NOT NULL,
    client integer NOT NULL
    );
     */
    /* services
    CREATE TABLE services (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    type varchar NOT NULL,
    length integer NOT NULL
    );

     */
}
